### ISSUE TITLE
the loss is nan

### ISSUE THREAD

**Issue by Clarence-wen** [vicwer/C3AE_Age_Estimation#10]
some of model.feats's  elements is negative number, because  the fc's  weights_initializer is between -limit to limit ,so  the kl_loss (tf.log  occur  nan) .  blow is my result:
model.feats:[[-0.17209125  0.07770187 -0.1429439  -0.94504386  0.09144928  0.40108332
   0.06493281 -0.5548259   0.21889538  0.43835896  0.28741086]] (1, 11)
kl_loss:[nan].
because there  Cannot be negative in tf.log,

**Comment by vicwer** [comment]
try softmax after model.feats
