### ISSUE TITLE
when running multi_gpus_train.py, invalidArgumentError occurs

### ISSUE THREAD

**Issue by alike123** [vicwer/C3AE_Age_Estimation#12]
(3, 64, 64, 3)
conv_1 (?, 62, 62, 32)
avg_1 (?, 31, 31, 32)
conv_2 (?, 29, 29, 32)
avg_2 (?, 14, 14, 32)
conv_3 (?, 12, 12, 32)
avg_3 (?, 6, 6, 32)
conv_4 (?, 4, 4, 32)
tower_0/C3AE/conv_5/truediv:0 (?, 4, 4, 32)
tower_0/C3AE/avg_pool:0 (?, 1, 1, 32)
reshape (?, 96)
fc_1 (?, 12)
fc_2 (?, 1)
Tensor("tower_0/C3AE/fc_1/kernel/Regularizer/l1_regularizer:0", shape=(), dtype=float32, device=/device:GPU:0)
/home/huhu/anaconda3/envs/tf12/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:108: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
2019-08-28 20:05:02.250645: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-08-28 20:05:02.912984: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties:
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:04:00.0
totalMemory: 11.91GiB freeMemory: 11.75GiB
2019-08-28 20:05:02.913034: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2019-08-28 20:05:03.342056: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-28 20:05:03.342115: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0
2019-08-28 20:05:03.342126: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N
2019-08-28 20:05:03.342558: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11366 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:04:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "/home/huhu/anaconda3/envs/tf12/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/home/huhu/anaconda3/envs/tf12/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/huhu/anaconda3/envs/tf12/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 168507 values, but the requested shape has 145200
         [[Node: Reshape = Reshape[T=DT_UINT8, Tshape=DT_INT32, _class=["loc:@random_flip_left_right/Switch_1"]](DecodeRaw, Reshape/shape)]]
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,3,64,64,3], [?,1], [?,12]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]
         [[Node: IteratorGetNext/_1 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_32_IteratorGetNext", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multi_gpus_train.py", line 144, in <module>
    train(finetune=False)
  File "multi_gpus_train.py", line 136, in train
    _, loss_, lr_ = sess.run([train_op, current_loss, learning_rate])
  File "/home/huhu/anaconda3/envs/tf12/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/home/huhu/anaconda3/envs/tf12/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/huhu/anaconda3/envs/tf12/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/home/huhu/anaconda3/envs/tf12/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 168507 values, but the requested shape has 145200
         [[Node: Reshape = Reshape[T=DT_UINT8, Tshape=DT_INT32, _class=["loc:@random_flip_left_right/Switch_1"]](DecodeRaw, Reshape/shape)]]
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,3,64,64,3], [?,1], [?,12]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]
         [[Node: IteratorGetNext/_1 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_32_IteratorGetNext", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'Reshape', defined at:
  File "multi_gpus_train.py", line 144, in <module>
    train(finetune=False)
  File "multi_gpus_train.py", line 76, in train
    imgs = tf.reshape(imgs, (-1, imgs.get_shape()[2], imgs.get_shape()[3], imgs.get_shape()[4]))
  File "/home/huhu/anaconda3/envs/tf12/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 6199, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/home/huhu/anaconda3/envs/tf12/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/huhu/anaconda3/envs/tf12/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/home/huhu/anaconda3/envs/tf12/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/home/huhu/anaconda3/envs/tf12/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Input to reshape is a tensor with 168507 values, but the requested shape has 145200
         [[Node: Reshape = Reshape[T=DT_UINT8, Tshape=DT_INT32, _class=["loc:@random_flip_left_right/Switch_1"]](DecodeRaw, Reshape/shape)]]
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,3,64,64,3], [?,1], [?,12]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]
         [[Node: IteratorGetNext/_1 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_32_IteratorGetNext", tensor_type=DT_FLOAT, `_device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

**Comment by alike123** [comment]
> 
> 
> (3, 64, 64, 3)
> conv_1 (?, 62, 62, 32)
> avg_1 (?, 31, 31, 32)
> conv_2 (?, 29, 29, 32)
> avg_2 (?, 14, 14, 32)
> conv_3 (?, 12, 12, 32)
> avg_3 (?, 6, 6, 32)
> conv_4 (?, 4, 4, 32)
> tower_0/C3AE/conv_5/truediv:0 (?, 4, 4, 32)
> tower_0/C3AE/avg_pool:0 (?, 1, 1, 32)
> reshape (?, 96)
> fc_1 (?, 12)
> fc_2 (?, 1)
> Tensor("tower_0/C3AE/fc_1/kernel/Regularizer/l1_regularizer:0", shape=(), dtype=float32, device=/device:GPU:0)
> /home/huhu/anaconda3/envs/tf12/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:108: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
> "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
> 2019-08-28 20:05:02.250645: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> 2019-08-28 20:05:02.912984: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties:
> name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
> pciBusID: 0000:04:00.0
> totalMemory: 11.91GiB freeMemory: 11.75GiB
> 2019-08-28 20:05:02.913034: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
> 2019-08-28 20:05:03.342056: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2019-08-28 20:05:03.342115: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0
> 2019-08-28 20:05:03.342126: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0: N
> 2019-08-28 20:05:03.342558: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11366 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:04:00.0, compute capability: 6.1)
> Traceback (most recent call last):
> File "/home/huhu/anaconda3/envs/tf12/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
> return fn(*args)
> File "/home/huhu/anaconda3/envs/tf12/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
> options, feed_dict, fetch_list, target_list, run_metadata)
> File "/home/huhu/anaconda3/envs/tf12/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
> run_metadata)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 168507 values, but the requested shape has 145200
> [[Node: Reshape = Reshape[T=DT_UINT8, Tshape=DT_INT32, _class=["loc:@random_flip_left_right/Switch_1"]](DecodeRaw, Reshape/shape)]]
> [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,3,64,64,3], [?,1], [?,12]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]
> [[Node: IteratorGetNext/_1 = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_32_IteratorGetNext", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "multi_gpus_train.py", line 144, in
> train(finetune=False)
> File "multi_gpus_train.py", line 136, in train
> _, loss_, lr_ = sess.run([train_op, current_loss, learning_rate])
> File "/home/huhu/anaconda3/envs/tf12/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 877, in run
> run_metadata_ptr)
> File "/home/huhu/anaconda3/envs/tf12/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1100, in _run
> feed_dict_tensor, options, run_metadata)
> File "/home/huhu/anaconda3/envs/tf12/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
> run_metadata)
> File "/home/huhu/anaconda3/envs/tf12/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
> raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 168507 values, but the requested shape has 145200
> [[Node: Reshape = Reshape[T=DT_UINT8, Tshape=DT_INT32, _class=["loc:@random_flip_left_right/Switch_1"]](DecodeRaw, Reshape/shape)]]
> [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,3,64,64,3], [?,1], [?,12]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]
> [[Node: IteratorGetNext/_1 = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_32_IteratorGetNext", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]]
> 
> Caused by op 'Reshape', defined at:
> File "multi_gpus_train.py", line 144, in
> train(finetune=False)
> File "multi_gpus_train.py", line 76, in train
> imgs = tf.reshape(imgs, (-1, imgs.get_shape()[2], imgs.get_shape()[3], imgs.get_shape()[4]))
> File "/home/huhu/anaconda3/envs/tf12/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 6199, in reshape
> "Reshape", tensor=tensor, shape=shape, name=name)
> File "/home/huhu/anaconda3/envs/tf12/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
> op_def=op_def)
> File "/home/huhu/anaconda3/envs/tf12/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
> return func(*args, **kwargs)
> File "/home/huhu/anaconda3/envs/tf12/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
> op_def=op_def)
> File "/home/huhu/anaconda3/envs/tf12/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1717, in **init**
> self._traceback = tf_stack.extract_stack()
> 
> InvalidArgumentError (see above for traceback): Input to reshape is a tensor with 168507 values, but the requested shape has 145200
> [[Node: Reshape = Reshape[T=DT_UINT8, Tshape=DT_INT32, _class=["loc:@random_flip_left_right/Switch_1"]](DecodeRaw, Reshape/shape)]]
> [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,3,64,64,3], [?,1], [?,12]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]
> [[Node: IteratorGetNext/_1 = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_32_IteratorGetNext", tensor_type=DT_FLOAT, `_device="/job:localhost/replica:0/task:0/device:GPU:0"]]

生成tfrecord时代码里将is_resize设为false了。
而且为什么设置的是resize为（96，96）呢？不是设置了height和width吗？而且后面读取tfrecord时也是解码成(220,220)的呀

**Comment by vicwer** [comment]
gen_data_batch.py中图像数据解码之后做了crop和resize

**Comment by cherry-sing** [comment]
hello,have you solved this problem？I encountered this problem too.
