### ISSUE TITLE
what is the exact different scales of one face?

### ISSUE THREAD

**Issue by MoonBunnyZZZ** [vicwer/C3AE_Age_Estimation#13]
In the paper,   three granularity levels images of one face were crop.What is the exact size of the three  images? @vicwer

**Comment by vicwer** [comment]
Sorry, I dont know exact size, try it...

**Comment by MoonBunnyZZZ** [comment]
> Sorry, I dont know exact size, try it...

So, how do you build train datasets to train model?

**Comment by vicwer** [comment]
background and head; no background and head; only face besides forehead

**Comment by alike123** [comment]
1.face detection. 2. expand the detected face by 10%.3. by 20%
