### ISSUE TITLE
About label

### ISSUE THREAD

**Issue by heyang1021** [vicwer/C3AE_Age_Estimation#15]
I don't undertand age_Yn_vector in label, could tell me what it is?

**Comment by heyang1021** [comment]
@vicwer

**Comment by vicwer** [comment]
```
import numpy as np

age = 68
age_vector = np.zeros(12)
age_vector[age//10] = (10 - age % 10) / 10
age_vector[age//10+1] = age % 10 / 10
```

**Comment by vicwer** [comment]
@heyang1021 
```
import numpy as np

age = 68
age_vector = np.zeros(12)
age_vector[age//10] = (10 - age % 10) / 10
age_vector[age//10+1] = age % 10 / 10
```

**Comment by heyang1021** [comment]
@vicwer Both age_vector[age//10] and age_vector[age//10+1] are zero? could you show me your train.txt? Just one line is enough. Thank you very much!

**Comment by vicwer** [comment]
@heyang1021 
like this:
```
face_0000001.png 68 0. 0. 0. 0. 0. 0. 0.2 0.8 0. 0. 0. 0. 
```
when age = 68, age_Yn_vector is `[0. , 0. , 0. , 0. , 0. , 0. , 0.2, 0.8, 0. , 0. , 0. , 0. ]`

**Comment by heyang1021** [comment]
@vicwer Get it, thank you！

**Comment by vicwer** [comment]
@heyang1021 good luck
