### ISSUE TITLE
comment error 

### ISSUE THREAD

**Issue by Tomasyao77** [vicwer/C3AE_Age_Estimation#19]
In file"models/network.py"
Line:69               # avg5 = tf.reduce_mean(conv5, [1, 2], keepdims=True, name='avg_pool')
Line:70               # print(avg5.name, avg5.get_shape())
Line:71               concat = reshape(conv5, [-1, avg5.get_shape()[3] * 3], 'reshape')
why do you comment Line:69?If so Line:71 will not get avg5.And I remove the "#" of Line:69，but it still doesn't work.
The error msg is "InvalidArgumentError (see above for traceback): Incompatible shapes: [60] vs. [960] [[node tower_0/loss_0/sub (defined at ../models/losses.py:14"
My img size is 220*220*3 when I produce tf_records.Thank you very much!

**Comment by vicwer** [comment]
@Tomasyao77 I am so sorry, I have no GPU now, so I cant run it, you can try it
```
def l1_loss(preds, labels):
    preds = tf.reshape(preds, (-1,))
    labels = tf.reshape(labels, (-1,))
    l1_loss = tf.abs(labels - preds)
    return tf.reduce_mean(l1_loss)

def kl_loss(preds, labels, l1):
    h_pq = -(tf.reduce_sum(tf.reduce_sum(labels * tf.log(preds + 1e-10), axis=1)))
    h_p = -tf.reduce_sum(labels * tf.log(labels + 1e-10))
    loss = h_pq - h_p + l1
    return -tf.reduce_mean(loss)
```
or, you could print the shape of every layer, and find the bug, thank you.
When I find the bug, I will tell you too.

**Comment by Tomasyao77** [comment]
> @Tomasyao77 I am so sorry, I have no GPU now, so I cant run it, you can try it
> 
> ```
> def l1_loss(preds, labels):
>     preds = tf.reshape(preds, (-1,))
>     labels = tf.reshape(labels, (-1,))
>     l1_loss = tf.abs(labels - preds)
>     return tf.reduce_mean(l1_loss)
> 
> def kl_loss(preds, labels, l1):
>     h_pq = -(tf.reduce_sum(tf.reduce_sum(labels * tf.log(preds + 1e-10), axis=1)))
>     h_p = -tf.reduce_sum(labels * tf.log(labels + 1e-10))
>     loss = h_pq - h_p + l1
>     return -tf.reduce_mean(loss)
> ```
> 
> or, you could print the shape of every layer, and find the bug, thank you.
> When I find the bug, I will tell you too.

Ok,thank you very much, I am debugging.

**Comment by vicwer** [comment]
@Tomasyao77 hello, I fixed it.
and, the Parametes of `Conv5->Feat` is 6156 in the paper, so `conv5->concat` instead of `conv5->avg5->concat`.

**Comment by Tomasyao77** [comment]
Wow! Wonderful! It does work well now,thanks you very much!

**Comment by vicwer** [comment]
good luck~
