### ISSUE TITLE
How can different scales of images share a plain CNN?

### ISSUE THREAD

**Issue by supernotman** [vicwer/C3AE_Age_Estimation#2]
I notice in the paper that different scales of  image cropped from the face are used.But how can they share the CNN network as they have different scale ?

**Comment by vicwer** [comment]
1. crop and resize images to 64x64x3
2. stack three images make its shape is 3x64x64x3, so the input data batch is (n,3,64,64,3)
3. reshape inputs to (nx3,64,64,3)
4. reshape features to (-1, c*3) before fully_connected layer

**Comment by supernotman** [comment]
> 1. crop and resize images to 64x64x3
> 2. stack three images make its shape is 3x64x64x3, so the input data batch is (n,3,64,64,3)
> 3. reshape inputs to (nx3,64,64,3)
> 4. reshape features to (-1, c*3) before fully_connected layer

Got it !Thanks
