### ISSUE TITLE
disscuss

### ISSUE THREAD

**Issue by signallee** [vicwer/C3AE_Age_Estimation#3]

**Comment by signallee** [comment]
may I ask a question? about the uniform interval K in the C3AE paper: K is set to 10; but the output size of the Feat layer in the plain model is 12. 
In my opinion, if age range from 0~100, the k is 10, the output size of Feat layer should be 11? match with W2

**Comment by vicwer** [comment]
I think the age range is 0 to 110 years old. According to your opinion, you can set the channel of fully connected layer to 11.

**Comment by signallee** [comment]
thx~
