### ISSUE TITLE
How to get img_list.txt and train.txt

### ISSUE THREAD

**Issue by kingroc711** [vicwer/C3AE_Age_Estimation#4]
|->img_list/img_list.txt
    |->train_list/train.txt
    |->dataset/*.png

**Comment by SongQingChe** [comment]
我不太确定train.txt中的‘img_path age_label age_Yn_vector’， 是不是‘1.jpg 18 0 0.2 0.8 0 0 0 0 0’ ?

**Comment by Clarence-wen** [comment]
age_Yn_vector是fc_1后的结果，应该是12维，我也是这里不太清楚

**Comment by SongQingChe** [comment]
我现在训练不了。。。ToT，不知道是不是train.txt生成的有问题

**Comment by SongQingChe** [comment]
这个gen_data_batch.py的16行和gen_tf_records_fast_to_uint8.py的26行都有错误，修改后运行multi_gpus_train.py报错Cannot convert a partially known TensorShape to a Tensor: (?,)......ToT

**Comment by Clarence-wen** [comment]
> 这个gen_data_batch.py的16行和gen_tf_records_fast_to_uint8.py的26行都有错误，修改后运行multi_gpus_train.py报错Cannot convert a partially known TensorShape to a Tensor: (?,)......ToT

跟我一样，也是这个错误

**Comment by SongQingChe** [comment]
这个是我修改的地方，凑合着能训练，你试试。





------------------ 原始邮件 ------------------
发件人: "Clarence-wen"<notifications@github.com>;
发送时间: 2019年7月4日(星期四) 凌晨0:23
收件人: "vicwer/C3AE_Age_Estimation"<C3AE_Age_Estimation@noreply.github.com>;
抄送: "宋清澈"<783336169@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [vicwer/C3AE_Age_Estimation] How to get img_list.txt andtrain.txt (#4)



 
这个gen_data_batch.py的16行和gen_tf_records_fast_to_uint8.py的26行都有错误，修改后运行multi_gpus_train.py报错Cannot convert a partially known TensorShape to a Tensor: (?,)......ToT
  
跟我一样，也是这个错误

**Comment by vicwer** [comment]
少了逗号。。。img_path要写绝对路径 @SongQingChe @Clarence-wen

**Comment by Clarence-wen** [comment]
哪个地方少了逗号，我的ｇｅｎ_data_bath.py运行没有问题，只是在计算l1_ｌｏｓｓ的ｔｆ.reduce_prod这里产生的上述的错误

------------------
黑夜给了我黑色的眼睛，而我却来寻找光
 

 





------------------ 原始邮件 ------------------
发件人: "KG.D"<notifications@github.com>;
发送时间: 2019年7月4日(星期四) 晚上9:27
收件人: "vicwer/C3AE_Age_Estimation"<C3AE_Age_Estimation@noreply.github.com>;
抄送: "斟酒自酌"<277844284@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [vicwer/C3AE_Age_Estimation] How to get img_list.txt andtrain.txt (#4)




少了逗号。。。img_path要写绝对路径 @SongQingChe @Clarence-wen

**Comment by vicwer** [comment]
这个地方你直接用config.py里的batch_size参数代替吧，就是求top_k有几个数的

**Comment by Clarence-wen** [comment]
> 这个地方你直接用config.py里的batch_size参数代替吧，就是求top_k有几个数的

恩恩，对的，可以训练了，谢谢

**Comment by Eajack** [comment]
> > 这个地方你直接用config.py里的batch_size参数代替吧，就是求top_k有几个数的
> 
> 恩恩，对的，可以训练了，谢谢

求问，如何生成'train.txt'

**Comment by wangxinyue11** [comment]
求生成txt的代码。。。。

**Comment by vicwer** [comment]
> 求生成txt的代码。。。。

##e.g.
```
import numpy as np
age = 68
age_vector = np.zeros(12)
age_vector[x//10+1] = x % 10 / 10
age_vector[x//10] = (10 - x % 10) / 10

path_and_label = ‘img_path ’ + str(age) + ' ' + ' '.join([str(i) for i in age_vector])
```

**Comment by vicwer** [comment]
> 求生成txt的代码。。。。



> > > 这个地方你直接用config.py里的batch_size参数代替吧，就是求top_k有几个数的
> > 
> > 
> > 恩恩，对的，可以训练了，谢谢
> 
> 求问，如何生成'train.txt'

e.g.
```
import numpy as np

age = 68
age_vector = np.zeros(12)
age_vector[x//10] = (10 - x % 10) / 10
age_vector[x//10+1] = x % 10 / 10

path_and_label = 'img_path' + ' ' + str(age) + ' ' + ' '.join([str(i) for i in age_vector]) 
```

**Comment by vicwer** [comment]
> > > 这个地方你直接用config.py里的batch_size参数代替吧，就是求top_k有几个数的
> > 
> > 
> > 恩恩，对的，可以训练了，谢谢
> 
> 求问，如何生成'train.txt'



> 求生成txt的代码。。。。

e.g.
```
import numpy as np

age = 68
age_vector = np.zeros(12)
age_vector[age//10] = (10 - age % 10) / 10
age_vector[age//10+1] = age % 10 / 10

path_and_label = 'img_path' + ' ' + str(age) + ' ' + ' '.join([str(i) for i in age_vector])
```

**Comment by mobilejammer** [comment]
> > > > 这个地方你直接用config.py里的batch_size参数代替吧，就是求top_k有几个数的
> > > 
> > > 
> > > 恩恩，对的，可以训练了，谢谢
> > 
> > 
> > 求问，如何生成'train.txt'
> 
> > 求生成txt的代码。。。。
> 
> e.g.
> 
> ```
> import numpy as np
> 
> age = 68
> age_vector = np.zeros(12)
> age_vector[age//10] = (10 - age % 10) / 10
> age_vector[age//10+1] = age % 10 / 10
> 
> path_and_label = 'img_path' + ' ' + str(age) + ' ' + ' '.join([str(i) for i in age_vector])
> ```

this is right , and why np.zeros(12). [0 10 20 30 40 50 60 70 80 90 100], total 11point no 12

**Comment by vicwer** [comment]
> > > > > 这个地方你直接用config.py里的batch_size参数代替吧，就是求top_k有几个数的
> > > > 
> > > > 
> > > > 恩恩，对的，可以训练了，谢谢
> > > 
> > > 
> > > 求问，如何生成'train.txt'
> > 
> > 
> > > 求生成txt的代码。。。。
> > 
> > 
> > e.g.
> > ```
> > import numpy as np
> > 
> > age = 68
> > age_vector = np.zeros(12)
> > age_vector[age//10] = (10 - age % 10) / 10
> > age_vector[age//10+1] = age % 10 / 10
> > 
> > path_and_label = 'img_path' + ' ' + str(age) + ' ' + ' '.join([str(i) for i in age_vector])
> > ```
> 
> this is right , and why np.zeros(12). [0 10 20 30 40 50 60 70 80 90 100], total 11point no 12

Some people can live to 110, so, [0 10 20 30 40 50 60 70 80 90 100 110], orz...

**Comment by alike123** [comment]
> 
> 
> > 这个gen_data_batch.py的16行和gen_tf_records_fast_to_uint8.py的26行都有错误，修改后运行multi_gpus_train.py报错Cannot convert a partially known TensorShape to a Tensor: (?,)......ToT
> 
> 跟我一样，也

> 
> 这个是我修改的地方，凑合着能训练，你试试。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Clarence-wen"<notifications@github.com>; 发送时间: 2019年7月4日(星期四) 凌晨0:23 收件人: "vicwer/C3AE_Age_Estimation"<C3AE_Age_Estimation@noreply.github.com>; 抄送: "宋清澈"<783336169@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [vicwer/C3AE_Age_Estimation] How to get img_list.txt andtrain.txt (#4) 这个gen_data_batch.py的16行和gen_tf_records_fast_to_uint8.py的26行都有错误，修改后运行multi_gpus_train.py报错Cannot convert a partially known TensorShape to a Tensor: (?,)......ToT 跟我一样，也是这个错误 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

请问这个错误您是怎么解决的呀，我也出现了一样的问题

**Comment by Clarence-wen** [comment]
> > > 这个gen_data_batch.py的16行和gen_tf_records_fast_to_uint8.py的26行都有错误，修改后运行multi_gpus_train.py报错Cannot convert a partially known TensorShape to a Tensor: (?,)......ToT
> > 
> > 
> > 跟我一样，也
> 
> > 这个是我修改的地方，凑合着能训练，你试试。
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "Clarence-wen"[notifications@github.com](mailto:notifications@github.com); 发送时间: 2019年7月4日(星期四) 凌晨0:23 收件人: "vicwer/C3AE_Age_Estimation"[C3AE_Age_Estimation@noreply.github.com](mailto:C3AE_Age_Estimation@noreply.github.com); 抄送: "宋清澈"[783336169@qq.com](mailto:783336169@qq.com);"Comment"[comment@noreply.github.com](mailto:comment@noreply.github.com); 主题: Re: [vicwer/C3AE_Age_Estimation] How to get img_list.txt andtrain.txt (#4) 这个gen_data_batch.py的16行和gen_tf_records_fast_to_uint8.py的26行都有错误，修改后运行multi_gpus_train.py报错Cannot convert a partially known TensorShape to a Tensor: (?,)......ToT 跟我一样，也是这个错误 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 请问这个错误您是怎么解决的呀，我也出现了一样的问题
前面有作者的回答，你细看下，我的就是tf.reduce_prod(l1_loss.get_shape()) 引起的，将其用ｂａｔｃｈ_size代替就可以了

**Comment by alike123** [comment]
> 
> 
> > > > 这个gen_data_batch.py的16行和gen_tf_records_fast_to_uint8.py的26行都有错误，修改后运行multi_gpus_train.py报错Cannot convert a partially known TensorShape to a Tensor: (?,)......ToT
> > > 
> > > 
> > > 跟我一样，也
> > 
> > 
> > > 这个是我修改的地方，凑合着能训练，你试试。
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: "Clarence-wen"[notifications@github.com](mailto:notifications@github.com); 发送时间: 2019年7月4日(星期四) 凌晨0:23 收件人: "vicwer/C3AE_Age_Estimation"[C3AE_Age_Estimation@noreply.github.com](mailto:C3AE_Age_Estimation@noreply.github.com); 抄送: "宋清澈"[783336169@qq.com](mailto:783336169@qq.com);"Comment"[comment@noreply.github.com](mailto:comment@noreply.github.com); 主题: Re: [vicwer/C3AE_Age_Estimation] How to get img_list.txt andtrain.txt (#4) 这个gen_data_batch.py的16行和gen_tf_records_fast_to_uint8.py的26行都有错误，修改后运行multi_gpus_train.py报错Cannot convert a partially known TensorShape to a Tensor: (?,)......ToT 跟我一样，也是这个错误 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
> > 
> > 
> > 请问这个错误您是怎么解决的呀，我也出现了一样的问题
> > 前面有作者的回答，你细看下，我的就是tf.reduce_prod(l1_loss.get_shape()) 引起的，将其用ｂａｔｃｈ_size代替就可以了



> 
> 
> > > > 这个gen_data_batch.py的16行和gen_tf_records_fast_to_uint8.py的26行都有错误，修改后运行multi_gpus_train.py报错Cannot convert a partially known TensorShape to a Tensor: (?,)......ToT
> > > 
> > > 
> > > 跟我一样，也
> > 
> > 
> > > 这个是我修改的地方，凑合着能训练，你试试。
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: "Clarence-wen"[notifications@github.com](mailto:notifications@github.com); 发送时间: 2019年7月4日(星期四) 凌晨0:23 收件人: "vicwer/C3AE_Age_Estimation"[C3AE_Age_Estimation@noreply.github.com](mailto:C3AE_Age_Estimation@noreply.github.com); 抄送: "宋清澈"[783336169@qq.com](mailto:783336169@qq.com);"Comment"[comment@noreply.github.com](mailto:comment@noreply.github.com); 主题: Re: [vicwer/C3AE_Age_Estimation] How to get img_list.txt andtrain.txt (#4) 这个gen_data_batch.py的16行和gen_tf_records_fast_to_uint8.py的26行都有错误，修改后运行multi_gpus_train.py报错Cannot convert a partially known TensorShape to a Tensor: (?,)......ToT 跟我一样，也是这个错误 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
> > 
> > 
> > 请问这个错误您是怎么解决的呀，我也出现了一样的问题
> > 前面有作者的回答，你细看下，我的就是tf.reduce_prod(l1_loss.get_shape()) 引起的，将其用ｂａｔｃｈ_size代替就可以了


> 
> 
> > > 这个gen_data_batch.py的16行和gen_tf_records_fast_to_uint8.py的26行都有错误，修改后运行multi_gpus_train.py报错Cannot convert a partially known TensorShape to a Tensor: (?,)......ToT
> > 
> > 
> > 跟我一样，也
> 
> > 这个是我修改的地方，凑合着能训练，你试试。
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "Clarence-wen"[notifications@github.com](mailto:notifications@github.com); 发送时间: 2019年7月4日(星期四) 凌晨0:23 收件人: "vicwer/C3AE_Age_Estimation"[C3AE_Age_Estimation@noreply.github.com](mailto:C3AE_Age_Estimation@noreply.github.com); 抄送: "宋清澈"[783336169@qq.com](mailto:783336169@qq.com);"Comment"[comment@noreply.github.com](mailto:comment@noreply.github.com); 主题: Re: [vicwer/C3AE_Age_Estimation] How to get img_list.txt andtrain.txt (#4) 这个gen_data_batch.py的16行和gen_tf_records_fast_to_uint8.py的26行都有错误，修改后运行multi_gpus_train.py报错Cannot convert a partially known TensorShape to a Tensor: (?,)......ToT 跟我一样，也是这个错误 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 请问这个错误您是怎么解决的呀，我也出现了一样的问题



> 
> 
> > > > 这个gen_data_batch.py的16行和gen_tf_records_fast_to_uint8.py的26行都有错误，修改后运行multi_gpus_train.py报错Cannot convert a partially known TensorShape to a Tensor: (?,)......ToT
> > > 
> > > 
> > > 跟我一样，也
> > 
> > 
> > > 这个是我修改的地方，凑合着能训练，你试试。
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: "Clarence-wen"[notifications@github.com](mailto:notifications@github.com); 发送时间: 2019年7月4日(星期四) 凌晨0:23 收件人: "vicwer/C3AE_Age_Estimation"[C3AE_Age_Estimation@noreply.github.com](mailto:C3AE_Age_Estimation@noreply.github.com); 抄送: "宋清澈"[783336169@qq.com](mailto:783336169@qq.com);"Comment"[comment@noreply.github.com](mailto:comment@noreply.github.com); 主题: Re: [vicwer/C3AE_Age_Estimation] How to get img_list.txt andtrain.txt (#4) 这个gen_data_batch.py的16行和gen_tf_records_fast_to_uint8.py的26行都有错误，修改后运行multi_gpus_train.py报错Cannot convert a partially known TensorShape to a Tensor: (?,)......ToT 跟我一样，也是这个错误 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
> > 
> > 
> > 请问这个错误您是怎么解决的呀，我也出现了一样的问题
> > 前面有作者的回答，你细看下，我的就是tf.reduce_prod(l1_loss.get_shape()) 引起的，将其用ｂａｔｃｈ_size代替就可以了

是在losses.py中改成这样吗
_, k_idx = tf.nn.top_k(kl_loss, tf.cast(tf.reduce_prod(kl_loss.get_shape()) * cfg.ohem_ratio, tf.int32))
可是我运行还是一样的错误呢

**Comment by Clarence-wen** [comment]
l1-loss和kl-loss的都要改，把里面的tf.reduce_prod，那里改成cfg.batch_size



---Original---

**Comment by alike123** [comment]
你好，请问这个C3AE的你测试的结果怎么样？我的测试结果好像不太准哎


Best regards!


来自：电子科大信号与信息处理系的胡佃敏。
地址：电子科技大学清水河校区
邮箱：dianminhu@163.com
On 8/27/2019 21:37，Clarence-wen<notifications@github.com> wrote：
l1-loss和kl-loss的都要改，把里面的tf.reduce_prod，那里改成cfg.batch_size



---Original---

**Comment by mobilejammer** [comment]
年龄本来就很难预测的准确，只要同张人脸比较变动比较小，各个年龄段区别比较明显就可以了、 



------------------ Original ------------------
