### ISSUE TITLE
Some confusion about the plain model

### ISSUE THREAD

**Issue by nancy006** [vicwer/C3AE_Age_Estimation#6]
Hi, @vicwer. I'm very confused about this sentence in the paper:' a fully connected layer with semantic distribution is inserted in between feature layer yn and the regression layer yn'. Does it mean that there are three fc layers or other changes in the ori plain model? Expect your answer.thx a lot.

**Comment by vicwer** [comment]
@nancy006 
feature layer:
```
concat = reshape(avg5, [-1, avg5.get_shape()[3] * 3], 'reshape')
```
fully connected layer:
```
feats = fully_connected(concat, 12, name='fc_1')
```
regression layer:
```
pred = fully_connected(feats, 1, name='fc_2')
```

**Comment by nancy006** [comment]
> @nancy006
> feature layer:
> 
> ```
> concat = reshape(avg5, [-1, avg5.get_shape()[3] * 3], 'reshape')
> ```
> 
> fully connected layer:
> 
> ```
> feats = fully_connected(concat, 12, name='fc_1')
> ```
> 
> regression layer:
> 
> ```
> pred = fully_connected(feats, 1, name='fc_2')
> ```

@vicwer ,thanks for your answer. it's useful. According to the two points representation of age, maybe 10 can be instead of 12. but my network does not work well. expect your result. thanks again.
