### ISSUE TITLE
Can anyone reproduce the mae as same as the papper

### ISSUE THREAD

**Issue by StevenBanama** [vicwer/C3AE_Age_Estimation#7]
I have try it in wiki and imdb, the result is far from expection. Can anyone reproduce it?

**Comment by chakri-muthyala** [comment]
Do you able to get age, more likely, as a combination of two values from **y**  ?

**Comment by vicwer** [comment]
```conv5->flatten(no pooling)->feats->...```
get better results

**Comment by cherry-sing** [comment]
The result in morph is still far from the paper,and can anyone reproduce it ?what is the mae usually?

**Comment by chakri-muthyala** [comment]
I got 3.15(Internal Evaluation).
