### ISSUE TITLE
Feat layer parameter count

### ISSUE THREAD

**Issue by chakri-muthyala** [vicwer/C3AE_Age_Estimation#8]
Can somebody explain the feat layer? How you able to get the same no.of parameter count as mentioned in the paper i.e.  6156?
@vicwer

thanks!!

**Comment by vicwer** [comment]
conv5(no pooling or reduce_mean) -> flatten -> Feat:
then params: 4*4*32 * 32 + 12 = 6156

**Comment by vicwer** [comment]
conv5(no pooling or reduce_mean) -> flatten -> Feat:
then params: 4 \times 4 \times 32 \times 32 + 12 = 6156

**Comment by vicwer** [comment]
conv5(no pooling or reduce_mean) -> flatten -> Feat:
then params: `4 * 4 * 32 * 32 + 12 = 6156`
