### ISSUE TITLE
gen_tf_records_fast_to_uint8.py has an error

### ISSUE THREAD

**Issue by alike123** [vicwer/C3AE_Age_Estimation#9]
`age_vector = float(line.strip().split(' ')[2:])`
TypeError: float() argument must be a string or a number, not 'list'
line.strip().split(' ')[2:]生成是一个list,直接对list进行强制类型转换不是会出错吗？
为什么你们好像都可以直接运行成功呢，是我的train.txt有错误吗

**Comment by vicwer** [comment]
可能他们运行时候改掉了
```[float(i) for i in line.strip().split(' ')[2:]]```
